pub mod ai;
pub mod collection;
pub mod completions;
pub mod config;
pub mod download;
pub mod list;
pub mod metadata;
pub mod search;
pub mod status;
pub mod tasks;
#[cfg(feature = "self-update")]
pub mod update;
pub mod upload;
